services:
  - type: web
    name: skillbridge-backend
    runtime: node
    rootDir: Backend
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGODB_URI
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: CLIENT_URL
        sync: false
      - key: EMAIL_USER
        sync: false
      - key: EMAIL_PASS
        sync: false

  - type: web
    name: skillbridge-frontend
    runtime: static
    rootDir: Frontend
    buildCommand: npm run build
    staticPublishPath: ./dist
    envVars:
      - key: NODE_ENV
        value: production
